Support to spritesheets without atlas and adjustable frames.
netgfx/phaser_modals pull request #13
Opened 2018-07-29 18:00 UTC by vitorregisrr

- Default atlasParent now is null (this wasnt fully necessary, but sometimes a blank string in a boolean test  make bugs), to then test if it was specified. If not specified, it will just call the sprite without the atlasParent. 

- The sprite now uses the frame option to call the respective spritesheet frame(with a normal index/number).

In my tests everything went fine without any bugs.

2018-07-30 05:44 UTC, netgfx requested changes
`modalLabel.frame = imageFrame;`

this should go inside the `else if` otherwise it is going to break the jsonAtlas part.

2018-07-30 15:39 UTC, vitorregisrr commented
you're right! changes will be made.

2018-07-30 18:35 UTC, netgfx approved these changes

2018-07-30 18:36 UTC, netgfx commented
closes #12

2018-08-21 21:52 UTC, vitorregisrr commented
why was it closed without a merge? there is something wrong? xD

2018-08-22 13:15 UTC, merged